# Generated by Django 5.2.4 on 2025-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idcarro', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('anofabricacao', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
