# Generated by Django 5.2.4 on 2025-07-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='marca',
        ),
    ]
