# Generated by Django 5.2.4 on 2025-07-10 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_remove_carro_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idmarca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='idmarca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carros_marca', to='carros.marca'),
        ),
    ]
