# Generated by Django 5.2.4 on 2025-07-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_marca_carro_idmarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='carros/fotos/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
